config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_items/index'
  # get 'wishlist_items/new'
  # get 'wishlist_items/create'
  get 'wishlist_items/destroy'

  resources :bookings, only: [ :index, :show ]
  # devise_for :users
  root to: 'listings#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :user, only: [ :new, :create ]
  resources :listings, except: [ :edit, :update, :destroy ] do
    resources :wishlist_items, only: [ :new, :create ]
    resources :bookings, except: [ :destroy ] do
      resources :reviews, except: [ :edit, :update, :destroy ]
    end
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_many :reviews, through: :bookings
  has_many :wishlist_items
  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch
  pg_search_scope :search_by_location,
                  against: :location,
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      # raise
      @listing = Listing.search_by_location(params[:query])
      @listing = Listing.near(params[:query], 20)
      # raise
      @listing_for_marker = @listing.where.not(latitude: nil, longitude: nil)
      @markers = @listing_for_marker.map do |listing|
      {
        lng: listing.longitude,
        lat: listing.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { listing: listing })
      }
    end
    else
    @listing = Listing.all
    @listing_for_marker = Listing.where.not(latitude: nil, longitude: nil)
      @markers = @listing_for_marker.map do |listing|
        {
          lng: listing.longitude,
          lat: listing.latitude,
          infoWindow: render_to_string(partial: "infowindow", locals: { listing: listing })
        }
      end
    end
  end


  def show
    @listing = Listing.find(params[:id])
    @booking = Booking.new
    @user = current_user
    @wishlist_item = WishlistItem.new
    @wishlist_check = WishlistItem.where(listing_id: @listing.id, user_id: current_user.id) unless current_user.nil?
    # raise
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    # raise
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
    # raise
  end

  private
  def listing_params
    params.require(:listing).permit(:title, :description, :photo, :location, :workhours, :kitchen, :price, :latitude, :longitude)
  end

end

app/views/listings/_infowindow.html.erb
    <p><strong><%= listing.title %></p></strong>
    <%=link_to "Find more about this desk", listing_path(listing)%>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/index.html.erb
<div class="wrapper-light-grey">
  <div class="card-container">

    <div class="row">
      <%= form_tag listings_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Try \"London\""
        %>
      <% end %>
      <div class="cards">
      <% @listing.each do |listing| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card">
            <%= link_to listing_path(listing) do %>
              <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url(<%= cl_image_path(listing.photo, width: 900, crop: :thumb) %>);">
                <span class="card-category"><%= listing.location %></span>
                <div class="card-description">
                  <h2><%= listing.title %></h2>
                </div>
              </div>
            <% end %>
              <div class="card-footer">
                <% if !current_user.nil? %>
                  <div class="wishlist-link">
                    <% wishlistclass = "wishlist-heart-clicked" if WishlistItem.where(listing_id: listing.id, user_id: current_user.id).any? %>

                    <%= link_to(listing_wishlist_items_path(listing.id), method: :post, remote: true) do %>
                      <i class="fa fa-heart wishlist-heart <%= wishlistclass %>" data-listing-id="<%= listing.id %>"></i>
                    <% end %>
                  </div>
                <% end %>
                <p>$<%= listing.price %> usd</p>
                <p> <%= listing.reviews.count %> Reviews (avg. <%= listing.reviews.average(:rating).to_f.round(1)%>)</p>
              </div>
            </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <div class="form_card">
        <h1>Add a Listing</h1>
        <!-- <p>Find me in app/views/listings/new.html.erb</p> -->

        <%= simple_form_for @listing do |f| %>
          <%= f.input :title %>
          <%= f.input :photo %>
          <%= f.input :description %>
          <%= f.input :location %>
          <%= f.input :workhours %>
          <%= f.input :kitchen, as: :boolean %>
          <%= f.input :price %>
          <%= f.submit "Add Listing", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <div class="listing-banner">
    <div class="info text-center">
      <h1><%= @listing.title.upcase %><br><br></h1>
      <p>£<%= @listing.price%>/DAY |
        <% @listing.reviews.average(:rating).to_f.round(0).times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <%= @listing.reviews.count %>
      </p>
    <h1>
      <% if !current_user.nil? %>
        <%= link_to(listing_wishlist_items_path(@listing), method: :post) do %>
          <% wishlistclass = "wishlist-heart-clicked" unless @wishlist_check.empty? %>
          <i class="fa fa-heart wishlist-heart <%= wishlistclass %>" id="wishlist-heart"></i>
          <!-- <i class="fa fa-heart"></i> -->
        <% end %>
      <% end %>
    </h1>
    </div>
    <div class="listing-photo">
      <img src="<%=cl_image_path(@listing.photo, width: 1600, crop: :fill) %>" alt="picture of desk">
    </div>
  </div>
</div>
<div class="container">
  <div class="listing-detail">
    <div class="details text-center">
      <div class="key-info ">
        <h3>Description</h3>
        <p><strong>Hosted by <%= @listing.user.name || @listing.user.first_name %></strong></p>
        <p><%= @listing.description%></p>
        <p><strong>Other Features:</strong></p>
          <ul style="list-style: none;">
            <li>You can work here from <%= @listing.workhours%></li>
            <li>
              <%= "You are allowed to use the kitchen" if @listing.kitchen%>
            </li>
          </ul>
        </div>

        <div class="reviews">
          <h3>Reviews</h3>
          <% @listing.reviews.each do |review| %>
          <div class="review_card">
            <h4>
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            </h4>
            <p> <%= review.content %><br><br><strong>-<%= review.booking.user.name %></strong></p>
          </div>
          <% end %>
        </div>

    </div>

  <div class="book">
    <div class="sticky-form">
      <div class="sticky-card">
        <div class="form_card text-center">
          <h1>Book this home</h1>
            <%= simple_form_for [@listing, @booking] do |f| %>
            <!-- , url: listing_bookings_path, method: :post  -->
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <%= f.submit "Book this desk", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

    </div>
  </div>
</div>
























    </div>
  </div>
</div>