config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_items/index'
  # get 'wishlist_items/new'
  # get 'wishlist_items/create'
  get 'wishlist_items/destroy'

  resources :bookings, only: [ :index, :show ]
  # devise_for :users
  root to: 'listings#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :user, only: [ :new, :create ]
  resources :listings, except: [ :edit, :update, :destroy ] do
    resources :wishlist_items, only: [ :new, :create ]
    resources :bookings, except: [ :destroy ] do
      resources :reviews, except: [ :edit, :update, :destroy ]
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :review
  belongs_to :listing
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @listings = Listing.all
    # raise
  end

  def show
    @booking = Booking.find(params[:id])
    # raise
  end

  def new
    @booking = Booking.new
    @listing = Listing.find(params[:listing_id])
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @booking = Booking.new(booking_params)
    @booking.listing = @listing
    @booking.user = current_user
    # raise
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    # raise
  end

  def update
    # raise
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :approved)
  end
end

app/views/bookings/_new_booking_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <div class="form_card">
        <h1>Book this home</h1>
        <p>Find me in app/views/bookings/new.html.erb</p>


        <%= simple_form_for @booking, url: listing_bookings_path, method: :post do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.submit "Book this desk", class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <div class="form_card">
        <h1>Approve booking</h1>
        <br>
        <%= simple_form_for @booking, url: listing_booking_path, method: :patch do |f| %>
          <%= f.input :approved, as: :radio_buttons, collection: [['confirmed', 'Approve'], ['rejected', 'Reject']], label: "", label_method: :second, value_method: :first %>
          <%#= f.input :approved, as: :boolean, input_html: { value: false }, checked_value: true, unchecked_value: false %>
          <br>
          <%= f.submit "Confirm ", class: "btn btn-primary" %>
        <% end %>
        </div>

    </div>
  </div>
</div>


<!-- , url: listing_bookings_path, method: :patch  -->

app/views/bookings/index.html.erb
<div class="wrapper-light-grey">
  <div class="card-container">
    <!-- <div class="row"> -->
      <div class="my_bookings">
        <h2>My next Deskos</h2>
        <div class="cards">
        <% @bookings.where(user: current_user).each do |booking| %>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <div class="card">
            <%= link_to listing_path(booking.listing) do %>
              <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url(<%= cl_image_path(booking.listing.photo, width: 900, crop: :thumb) %>);">
                <span class="card-category"><%= booking.listing.location %></span>
                <div class="card-description">
                  <h2><%= booking.listing.title %></h2>
                </div>
              </div>
            <% end %>
              <div class="card-footer">
                  <div class="wishlist-link">
                    <a href="#"><i class="fa fa-heart"></i></a>
                  </div>
                  <p>
                    Booking status
                  <% if booking.approved == "confirmed"  %>
                    <%= "Accepted" %>
                    <% if booking.review.nil?  %>
                      <%= link_to "New review", new_listing_booking_review_path(booking.listing, booking), class: "btn btn-primary btn-sm" %>
                    <% else %>
                      <%= link_to "View my review", listing_path(booking.listing) %>
                    <% end %>
                  <% else %>
                    <%= booking.approved.titlecase %>
                  <% end %>
                  </p>
                  <p> From: <%= booking.start_date %> To: <%= booking.end_date %></p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    <!-- </div> -->
<!--     <div class="row">
 -->

 <div class="my_bookings">
    <h2>Requests for my listings</h2>
        <div class="cards">
        <% @listings.where(user: current_user).each do |listing| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card">
            <%= link_to listing_path(listing) do %>
              <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url(<%= cl_image_path(listing.photo, width: 900, crop: :thumb) %>);">
                <span class="card-category"><%= listing.location %></span>
                <div class="card-description">
                  <h2><%= listing.title %></h2>
                </div>
              </div>
            <% end %>
              <div class="card-footer">
                  <div class="wishlist-link">
                    <a href="#"><i class="fa fa-heart"></i></a>
                  </div>
                  <p>Booking status
                    <% listing.bookings.each do |booking| %>
                  <% if booking.approved == "pending" %>
                    <%= link_to "Pending", edit_listing_booking_path(booking.listing, booking) %>
                  <% else %>
                    <%= booking.approved.titlecase %>
                  <% end %></p>
                  <p> From: <%= booking.start_date %> To: <%= booking.end_date %></p>
              </div>
                  <% end %>
            </div>
          </div>
        <% end %>
      </div>
 </div>

<!--     </div>
 -->
</div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <div class="form_card">
        <h1>Book this home</h1>
        <p>Find me in app/views/bookings/new.html.erb</p>


        <%= simple_form_for @booking, url: listing_bookings_path, method: :post do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.submit "Book this desk", class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>


<%= @booking %>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>