config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_items/index'
  # get 'wishlist_items/new'
  # get 'wishlist_items/create'
  get 'wishlist_items/destroy'

  resources :bookings, only: [ :index, :show ]
  # devise_for :users
  root to: 'listings#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :user, only: [ :new, :create ]
  resources :listings, except: [ :edit, :update, :destroy ] do
    resources :wishlist_items, only: [ :new, :create ]
    resources :bookings, except: [ :destroy ] do
      resources :reviews, except: [ :edit, :update, :destroy ]
    end
  end
end

app/views/pages/_navbar.html.erb
<div class="navbar-desko">
    <a href="#">
      <%= link_to root_path do %>
        <%= image_tag('DESKO.jpg') %>
      <% end %>
    </a>
  <div class="navbar-desko-actions d-none d-sm-flex">
   <% if user_signed_in? %>
      <div class="my-navbar-container">
        Logged in as <%= current_user.first_name || current_user.name%>

          <div class="navbar-right">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-desko-link'  %>
            <%= link_to "Add a listing", new_listing_path, :class => 'navbar-desko-link' %>  <%= link_to "View your bookings", bookings_path, :class => 'navbar-desko-link' %>
            <%= link_to(wishlist_items_index_path) do  %>
              <i class="fa fa-heart navbar-desko-link"></i>
            <% end %>
          </div>
      </div>

      <% else %>
         <%= link_to "Login", new_user_session_path, :class => 'navbar-desko-link'  %>
         <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-desko-link'%>
      <% end %>
  </div>
</div>