config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_items/index'
  # get 'wishlist_items/new'
  # get 'wishlist_items/create'
  get 'wishlist_items/destroy'

  resources :bookings, only: [ :index, :show ]
  # devise_for :users
  root to: 'listings#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :user, only: [ :new, :create ]
  resources :listings, except: [ :edit, :update, :destroy ] do
    resources :wishlist_items, only: [ :new, :create ]
    resources :bookings, except: [ :destroy ] do
      resources :reviews, except: [ :edit, :update, :destroy ]
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @listing = Listing.find(params[:listing_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:booking_id, :content, :rating)
  end
end

app/views/reviews/index.html.erb
<!-- THIS PAGE WILL DISPLAY ALL THE REVIEWS TO A GIVEN PROPERTY BY ITS ID

URL: LISTINGS/LISTING:ID/BOOKINGS/BOOKING:ID/REVIEWS -->

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h3>Reviews</h3>
      <ul style="list-style: none" class="list-group">
        <% @reviews.each do |review| %>
          <li class="list-group-item">
            <%= review.content %>
          </li>
          <li>
            <%= review.rating.times do %>
            <i class="fas fa-star"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<!-- if review id == booking id
display reviews -->

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <div class="form_card">
        <h3>Add a review for <%= @booking.listing.title %></h3>
        <%= simple_form_for @review, url: listing_booking_reviews_path, method: :post do |f| %>
          <%= f.input :content %>
          <%= f.collection_radio_buttons :rating, [[1], [2], [3], [4], [5]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b| %>
            <%= b.radio_button + b.label {''} %>
          <% end %>
        <br>
        <br>
          <%= f.submit "Add Review", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Had issues adding stars to form. Not a priority. Have left it.  -->
<!-- <input class="star" type="checkbox" title="bookmark page"><br/><br/> -->